### PR TITLE
vendor golang.org/x/crypto using glide

### PR DESCRIPTION
**Pull request by lsm5**
This would help us build go-mtree on RHEL/CentOS and
distros where golang.org/x/crypto isn't provided or supported.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@vbatts vendored dep using glide, PTAL. Closing https://github.com/vbatts/go-mtree/pull/75 in favor of this.

### CODE REVIEW

**Comment by vbatts** [comment]
we'll need to exclude some paths from our `go test -v ./...`. It looks like one of the vendored deps has a failing test. I wonder if glide can prune out _test.go files

**Comment by lsm5** [comment]
seems unlikely, would it be ok perhaps if we set .travis.yml to skip failing tests (don't know if that's doable)?

**Comment by vbatts** [comment]
@lsm5 what glide command did you run to produce this and lock it?

**Comment by lsm5** [comment]
GOPATH=/usr/share/gocode:$(pwd) glide init
GOPATH=/usr/share/gocode:$(pwd) glide install
GOPATH=/usr/share/gocode:$(pwd) glide remove github.com/vbatts/go-mtree # (else this would show up in vendor/ too)

**Comment by lsm5** [comment]
I'm able to build this using vendored deps in RHEL now. Thanks a lot!!

btw, could you move this into @projectatomic?? /cc @rhatdan

**Comment by vbatts** [comment]
maybe eventually, but not yet

**Comment by rhatdan** [comment]
It is fine with me to move it once Vincent gives the ok.

**Pull request closed without merging**
