### PR TITLE
cmd: fix single-dash flag

### PR DESCRIPTION
**Pull request by cyphar**
Single dash flags are the _worst_.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by stephen679** [comment]
golang's `flag` package does not recognize options that start with "--". we could use [](https://github.com/ogier/pflag) to resolve this.

**Comment by vbatts** [comment]
haha. picky picky. I figured you'd be used to the single dash flags by now. :-)

**Comment by cyphar** [comment]
Or we should just switch to Cobra. Currently the help information is also incredibly ugly.

**Comment by vbatts** [comment]
so https://github.com/spf13/cobra i've never directly touched. I have used https://github.com/codegangsta/cli before

**Comment by vbatts** [comment]
@cyphar i'm down for what ever. I generally like _not_ having to vendor anything. Do either of these choices have a history for a consistent API in master?

**Comment by vbatts** [comment]
I'm going to close this for now, as just adding a dash does not accomplish everything. And overhauling flag parser would happen in a follow-up PR

**Pull request closed without merging**
