### PR TITLE
*: xattr can Update()

### PR DESCRIPTION
**Pull request by vbatts**
This is a gnarly patchset that has been mashed together.
It uncovered that some aspects of Check were never really working
correctly for `xattr` keywords, but also the `Update()` had been left
undone for a while.

This includes some API changes around the `Keyword` and `KeyVal` types.

Also I would like to update the signature for the `UpdateKeywordFunc` to
just accept a `KeyVal` as an argugment, rather than a keyword AND the
value. with this context there would be no need to guess on the value of
what's passed to the xattr update function of whether it needs or
already is base64 encoded.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
cc @cyphar

**Comment by vbatts** [comment]
tests pass.

**Comment by cyphar** [comment]
Sorry for not reviewing this earlier (I had exams the past few days). I'll take a look at this and send a patch if necessary. :smile_cat:

**Comment by vbatts** [comment]
I realized this too, so I didn't wait

**Pull request merged**
