### PR TITLE
tar: resolve hardlinks when streaming archive

### PR DESCRIPTION
**Pull request by stephen679**
Previously, Entry's associated with a hardlink to another file did not contain the correct data, in that the data did not represent the actual file that they are hardlinked to. This commit keeps track of hardlink files using `archive/tar`'s `Typeflag` constant.

Signed-off-by: Stephen Chung <schung@redhat.com>

### CODE REVIEW

**Comment by stephen679** [comment]
fixes #59

**Comment by vbatts** [comment]
LGTM

I wonder if we shouldn't now include `nlink` in the default keywords for tar archives?

**Comment by stephen679** [comment]
Did you mean if we should include nlinks now?

**Comment by stephen679** [comment]
Also, this PR doesn't count the number of hardlinks a directory has (apparently `# of nlinks of dir == # of sub-directories + 2`?)

**Pull request merged**
