### PR TITLE
compare: return the right delta

### PR DESCRIPTION
**Pull request by tych0**
Heh, copypasta error. Amazing I'm the first person who noticed this :)

Signed-off-by: Tycho Andersen <tycho@tycho.ws>

### CODE REVIEW

**Comment by vbatts** [comment]
omg

**Comment by vbatts** [comment]
unrelated issues with validation :-\

**Comment by tych0** [comment]
Yeah, weird? Did it get deleted from github or something?

**Comment by vbatts** [comment]
@tych0 do you mind rebasing on master?

**Comment by tych0** [comment]
Should be done, let's see what travis thinks :)

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
