### PR TITLE
vendor golang.org/x/crypto using hack/vendor.sh

### PR DESCRIPTION
**Pull request by lsm5**
vendor.sh credit to github.com/docker/docker

Signed-off-by: Lokesh Mandvekar lsm5@fedoraproject.org

@vbatts PTAL

### CODE REVIEW

**Comment by vbatts** [comment]
hrmm. I'm not entirely sure I want to do this. 
The only external import `go.crypto/ripemd160` is not likely to break on `go get`. 
And the import path seems to have something broken with it. Not sure what to recommend here.

**Comment by lsm5** [comment]
how's it sound if I only keep the ripemd160 dir and delete all the rest?

**Comment by vbatts** [comment]
I wonder if looking at tools like glide or godeps would make this easier

**Comment by lsm5** [comment]
godeps doesn't seem to work on rawhide in that it just creates a useless Godeps.json with info about go version, haven't tried glide yet but I will now.

@runcom mentioned he switched to hack/vendor.sh so that's why this PR.

**Comment by lsm5** [comment]
@vbatts by "import path seems to have something broken with it", is it because golang.org/x/crypto has now moved to github.com/golang/crypto? I added a symlink for that to the old path.

**Comment by vbatts** [comment]
@lsm5 the import path is not bound to the place where development occurs. The import path is still `golang.org/x/crypto`

**Comment by vbatts** [comment]
@lsm5 i'm still not sure what to do with this for now. The import paths don't line up, and the vendoring is not yet a requirement for this project as `golang.org/x/crypto` API has not diverged.
Thoughts?

**Comment by cyphar** [comment]
For `umoci`, I've been using `glide` with some components from `hack/vendor.sh` to clean up unimported paths. Take a look: https://github.com/cyphar/umoci/blob/master/hack/vendor.sh

**Comment by lsm5** [comment]
@vbatts keywords.go uses `golang.org/x/crypto/ripemd160` but it seems crypto lib is now at github.com/golang/crypto . Also, vendoring the package will help to build gomtree without requiring a separate package for golang crypto on RHEL and downstreams.

@cyphar thanks, I'll take a look.

**Comment by vbatts** [comment]
@lsm5 understand the confusion. The canonical path for the `golang.org/x/...` repos is _different_ from where the source might be mirrored. This is a choice they've made for future proofing against a switch from hosting code on github, etc.

**Pull request closed without merging**
